<?php /*

[literal]
AvailableClasses[]=abap
AvailableClasses[]=actionscript
AvailableClasses[]=actionscript3
AvailableClasses[]=ada
AvailableClasses[]=algol68
AvailableClasses[]=apache
AvailableClasses[]=applescript
AvailableClasses[]=apt_sources
AvailableClasses[]=asm
AvailableClasses[]=asp
AvailableClasses[]=autoconf
AvailableClasses[]=autohotkey
AvailableClasses[]=autoit
AvailableClasses[]=avisynth
AvailableClasses[]=awk
AvailableClasses[]=bascomavr
AvailableClasses[]=bash
AvailableClasses[]=basic4gl
AvailableClasses[]=bibtex
AvailableClasses[]=blitzbasic
AvailableClasses[]=bnf
AvailableClasses[]=boo
AvailableClasses[]=bf
AvailableClasses[]=c
AvailableClasses[]=csharp
AvailableClasses[]=c_loadrunner
AvailableClasses[]=c_mac
AvailableClasses[]=cpp
AvailableClasses[]=cpp-qt
AvailableClasses[]=caddcl
AvailableClasses[]=cadlisp
AvailableClasses[]=cfdg
AvailableClasses[]=chaiscript
AvailableClasses[]=cil
AvailableClasses[]=clojure
AvailableClasses[]=cmake
AvailableClasses[]=cobol
AvailableClasses[]=coffeescript
AvailableClasses[]=cfm
AvailableClasses[]=css
AvailableClasses[]=cuesheet
AvailableClasses[]=d
AvailableClasses[]=dcs
AvailableClasses[]=delphi
AvailableClasses[]=diff
AvailableClasses[]=div
AvailableClasses[]=dos
AvailableClasses[]=dot
AvailableClasses[]=e
AvailableClasses[]=ecmascript
AvailableClasses[]=eiffel
AvailableClasses[]=email
AvailableClasses[]=epc
AvailableClasses[]=erlang
AvailableClasses[]=euphoria
AvailableClasses[]=ezini
AvailableClasses[]=eztemplate
AvailableClasses[]=fsharp
AvailableClasses[]=falcon
AvailableClasses[]=fo
AvailableClasses[]=f1
AvailableClasses[]=fortran
AvailableClasses[]=freebasic
AvailableClasses[]=4cs
AvailableClasses[]=gambas
AvailableClasses[]=gdb
AvailableClasses[]=genero
AvailableClasses[]=genie
AvailableClasses[]=glsl
AvailableClasses[]=gml
AvailableClasses[]=gettext
AvailableClasses[]=make
AvailableClasses[]=gnuplot
AvailableClasses[]=go
AvailableClasses[]=groovy
AvailableClasses[]=gwbasic
AvailableClasses[]=haskell
AvailableClasses[]=hicest
AvailableClasses[]=hq9plus
AvailableClasses[]=html4strict
AvailableClasses[]=html5
AvailableClasses[]=icon
AvailableClasses[]=ini
AvailableClasses[]=inno
AvailableClasses[]=intercal
AvailableClasses[]=io
AvailableClasses[]=j
AvailableClasses[]=java
AvailableClasses[]=java5
AvailableClasses[]=javascript
AvailableClasses[]=jquery
AvailableClasses[]=kixtart
AvailableClasses[]=klonec
AvailableClasses[]=klonecpp
AvailableClasses[]=latex
AvailableClasses[]=lb
AvailableClasses[]=lisp
AvailableClasses[]=llvm
AvailableClasses[]=locobasic
AvailableClasses[]=logtalk
AvailableClasses[]=lolcode
AvailableClasses[]=lotusformulas
AvailableClasses[]=lotusscript
AvailableClasses[]=lscript
AvailableClasses[]=lsl2
AvailableClasses[]=lua
AvailableClasses[]=magiksf
AvailableClasses[]=mapbasic
AvailableClasses[]=matlab
AvailableClasses[]=mpasm
AvailableClasses[]=reg
AvailableClasses[]=mirc
AvailableClasses[]=mmix
AvailableClasses[]=modula2
AvailableClasses[]=modula3
AvailableClasses[]=6502acme
AvailableClasses[]=6502kickass
AvailableClasses[]=6502tasm
AvailableClasses[]=68000devpac
AvailableClasses[]=m68k
AvailableClasses[]=mxml
AvailableClasses[]=mysql
AvailableClasses[]=newlisp
AvailableClasses[]=nsis
AvailableClasses[]=oberon2
AvailableClasses[]=objeck
AvailableClasses[]=objc
AvailableClasses[]=ocaml
AvailableClasses[]=ocaml-brief
AvailableClasses[]=pf
AvailableClasses[]=oobas
AvailableClasses[]=oracle8
AvailableClasses[]=oracle11
AvailableClasses[]=oxygene
AvailableClasses[]=oz
AvailableClasses[]=pascal
AvailableClasses[]=pcre
AvailableClasses[]=per
AvailableClasses[]=perl
AvailableClasses[]=perl6
AvailableClasses[]=php
AvailableClasses[]=php-brief
AvailableClasses[]=pic16
AvailableClasses[]=pike
AvailableClasses[]=pixelbender
AvailableClasses[]=pli
AvailableClasses[]=plsql
AvailableClasses[]=postgresql
AvailableClasses[]=povray
AvailableClasses[]=powerbuilder
AvailableClasses[]=powershell
AvailableClasses[]=proftpd
AvailableClasses[]=progress
AvailableClasses[]=prolog
AvailableClasses[]=properties
AvailableClasses[]=providex
AvailableClasses[]=purebasic
AvailableClasses[]=python
AvailableClasses[]=pycon
AvailableClasses[]=q
AvailableClasses[]=qbasic
AvailableClasses[]=rsplus
AvailableClasses[]=rails
AvailableClasses[]=rebol
AvailableClasses[]=robots
AvailableClasses[]=rpmspec
AvailableClasses[]=ruby
AvailableClasses[]=sas
AvailableClasses[]=scala
AvailableClasses[]=scheme
AvailableClasses[]=scilab
AvailableClasses[]=sdlbasic
AvailableClasses[]=smalltalk
AvailableClasses[]=smarty
AvailableClasses[]=sql
AvailableClasses[]=systemverilog
AvailableClasses[]=tsql
AvailableClasses[]=tcl
AvailableClasses[]=teraterm
AvailableClasses[]=text
AvailableClasses[]=thinbasic
AvailableClasses[]=typoscript
AvailableClasses[]=unicon
AvailableClasses[]=idl
AvailableClasses[]=uscript
AvailableClasses[]=vala
AvailableClasses[]=vbnet
AvailableClasses[]=verilog
AvailableClasses[]=vhdl
AvailableClasses[]=vim
AvailableClasses[]=vb
AvailableClasses[]=visualfoxpro
AvailableClasses[]=visualprolog
AvailableClasses[]=whitespace
AvailableClasses[]=whois
AvailableClasses[]=winbatch
AvailableClasses[]=xpp
AvailableClasses[]=xbasic
AvailableClasses[]=xml
AvailableClasses[]=xorg_conf
AvailableClasses[]=yaml
AvailableClasses[]=z80
AvailableClasses[]=zxbasic
ClassDescription[abap]=ABAP
ClassDescription[actionscript]=ActionScript
ClassDescription[actionscript3]=ActionScript 3
ClassDescription[ada]=Ada
ClassDescription[algol68]=ALGOL 68
ClassDescription[apache]=Apache configuration
ClassDescription[applescript]=AppleScript
ClassDescription[apt_sources]=Apt sources
ClassDescription[asm]=ASM
ClassDescription[asp]=ASP
ClassDescription[autoconf]=Autoconf
ClassDescription[autohotkey]=Autohotkey
ClassDescription[autoit]=AutoIt
ClassDescription[avisynth]=AviSynth
ClassDescription[awk]=awk
ClassDescription[bascomavr]=BASCOM AVR
ClassDescription[bash]=Bash
ClassDescription[basic4gl]=Basic4GL
ClassDescription[bibtex]=BibTeX
ClassDescription[blitzbasic]=BlitzBasic
ClassDescription[bnf]=bnf
ClassDescription[boo]=Boo
ClassDescription[bf]=Brainfuck
ClassDescription[c]=C
ClassDescription[csharp]=C#
ClassDescription[c_loadrunner]=C (LoadRunner)
ClassDescription[c_mac]=C (Mac)
ClassDescription[cpp]=C++
ClassDescription[cpp-qt]=C++ (QT)
ClassDescription[caddcl]=CAD DCL
ClassDescription[cadlisp]=CAD Lisp
ClassDescription[cfdg]=CFDG
ClassDescription[chaiscript]=ChaiScript
ClassDescription[cil]=CIL
ClassDescription[clojure]=Clojure
ClassDescription[cmake]=CMake
ClassDescription[cobol]=COBOL
ClassDescription[coffeescript]=CoffeeScript
ClassDescription[cfm]=ColdFusion
ClassDescription[css]=CSS
ClassDescription[cuesheet]=Cuesheet
ClassDescription[d]=D
ClassDescription[dcs]=DCS
ClassDescription[delphi]=Delphi
ClassDescription[diff]=Diff
ClassDescription[div]=DIV
ClassDescription[dos]=DOS
ClassDescription[dot]=dot
ClassDescription[e]=E
ClassDescription[ecmascript]=ECMAScript
ClassDescription[eiffel]=Eiffel
ClassDescription[email]=eMail (mbox)
ClassDescription[epc]=EPC
ClassDescription[erlang]=Erlang
ClassDescription[euphoria]=Euphoria
ClassDescription[ezini]=eZ Publish ini
ClassDescription[eztemplate]=eZ Publish template
ClassDescription[fsharp]=F#
ClassDescription[falcon]=Falcon
ClassDescription[fo]=FO (abas-ERP)
ClassDescription[f1]=Formula One
ClassDescription[fortran]=Fortran
ClassDescription[freebasic]=FreeBasic
ClassDescription[4cs]=GADV 4CS
ClassDescription[gambas]=GAMBAS
ClassDescription[gdb]=GDB
ClassDescription[genero]=genero
ClassDescription[genie]=Genie
ClassDescription[glsl]=glSlang
ClassDescription[gml]=GML
ClassDescription[gettext]=GNU Gettext
ClassDescription[make]=GNU make
ClassDescription[gnuplot]=Gnuplot
ClassDescription[go]=Go
ClassDescription[groovy]=Groovy
ClassDescription[gwbasic]=GwBasic
ClassDescription[haskell]=Haskell
ClassDescription[hicest]=HicEst
ClassDescription[hq9plus]=HQ9+
ClassDescription[html4strict]=HTML
ClassDescription[html5]=HTML
ClassDescription[icon]=Icon
ClassDescription[ini]=INI
ClassDescription[inno]=Inno
ClassDescription[intercal]=INTERCAL
ClassDescription[io]=Io
ClassDescription[j]=J
ClassDescription[java]=Java
ClassDescription[java5]=Java(TM) 2 Platform Standard Edition 5.0
ClassDescription[javascript]=Javascript
ClassDescription[jquery]=jQuery
ClassDescription[kixtart]=KiXtart
ClassDescription[klonec]=KLone C
ClassDescription[klonecpp]=KLone C++
ClassDescription[latex]=LaTeX
ClassDescription[lb]=Liberty BASIC
ClassDescription[lisp]=Lisp
ClassDescription[llvm]=LLVM Intermediate Representation
ClassDescription[locobasic]=Locomotive Basic
ClassDescription[logtalk]=Logtalk
ClassDescription[lolcode]=LOLcode
ClassDescription[lotusformulas]=Lotus Notes @Formulas
ClassDescription[lotusscript]=LotusScript
ClassDescription[lscript]=LScript
ClassDescription[lsl2]=LSL2
ClassDescription[lua]=Lua
ClassDescription[magiksf]=MagikSF
ClassDescription[mapbasic]=MapBasic
ClassDescription[matlab]=Matlab M
ClassDescription[mpasm]=Microchip Assembler
ClassDescription[reg]=Microsoft Registry
ClassDescription[mirc]=mIRC Scripting
ClassDescription[mmix]=MMIX
ClassDescription[modula2]=Modula-2
ClassDescription[modula3]=Modula-3
ClassDescription[6502acme]=MOS 6502 (6510) ACME Cross Assembler format
ClassDescription[6502kickass]=MOS 6502 (6510) Kick Assembler format
ClassDescription[6502tasm]=MOS 6502 (6510) TASM/64TASS 1.46 Assembler format
ClassDescription[68000devpac]=Motorola 68000 - HiSoft Devpac ST 2 Assembler format
ClassDescription[m68k]=Motorola 68000 Assembler
ClassDescription[mxml]=MXML
ClassDescription[mysql]=MySQL
ClassDescription[newlisp]=newlisp
ClassDescription[nsis]=NSIS
ClassDescription[oberon2]=Oberon-2
ClassDescription[objeck]=Objeck Programming Language
ClassDescription[objc]=Objective-C
ClassDescription[ocaml]=OCaml
ClassDescription[ocaml-brief]=OCaml (brief)
ClassDescription[pf]=OpenBSD Packet Filter
ClassDescription[oobas]=OpenOffice.org Basic
ClassDescription[oracle8]=Oracle 8 SQL
ClassDescription[oracle11]=Oracle 11 SQL
ClassDescription[oxygene]=Oxygene (Delphi Prism)
ClassDescription[oz]=OZ
ClassDescription[pascal]=Pascal
ClassDescription[pcre]=PCRE
ClassDescription[per]=per
ClassDescription[perl]=Perl
ClassDescription[perl6]=Perl 6
ClassDescription[php]=PHP
ClassDescription[php-brief]=PHP (brief)
ClassDescription[pic16]=PIC16
ClassDescription[pike]=Pike
ClassDescription[pixelbender]=Pixel Bender 1.0
ClassDescription[pli]=PL/I
ClassDescription[plsql]=PL/SQL
ClassDescription[postgresql]=PostgreSQL
ClassDescription[povray]=POVRAY
ClassDescription[powerbuilder]=PowerBuilder
ClassDescription[powershell]=PowerShell
ClassDescription[proftpd]=ProFTPd configuration
ClassDescription[progress]=Progress
ClassDescription[prolog]=Prolog
ClassDescription[properties]=PROPERTIES
ClassDescription[providex]=ProvideX
ClassDescription[purebasic]=PureBasic
ClassDescription[python]=Python
ClassDescription[pycon]=Python (console mode)
ClassDescription[q]=q/kdb+
ClassDescription[qbasic]=QBasic/QuickBASIC
ClassDescription[rsplus]=R / S+
ClassDescription[rails]=Rails
ClassDescription[rebol]=REBOL
ClassDescription[robots]=robots.txt
ClassDescription[rpmspec]=RPM Specification File
ClassDescription[ruby]=Ruby
ClassDescription[sas]=SAS
ClassDescription[scala]=Scala
ClassDescription[scheme]=Scheme
ClassDescription[scilab]=SciLab
ClassDescription[sdlbasic]=sdlBasic
ClassDescription[smalltalk]=Smalltalk
ClassDescription[smarty]=Smarty
ClassDescription[sql]=SQL
ClassDescription[systemverilog]=SystemVerilog
ClassDescription[tsql]=T-SQL
ClassDescription[tcl]=TCL
ClassDescription[teraterm]=Tera Term Macro
ClassDescription[text]=Text
ClassDescription[thinbasic]=thinBasic
ClassDescription[typoscript]=TypoScript
ClassDescription[unicon]=Unicon (Unified Extended Dialect of Icon)
ClassDescription[idl]=Uno Idl
ClassDescription[uscript]=Unreal Script
ClassDescription[vala]=Vala
ClassDescription[vbnet]=vb.net
ClassDescription[verilog]=Verilog
ClassDescription[vhdl]=VHDL
ClassDescription[vim]=Vim Script
ClassDescription[vb]=Visual Basic
ClassDescription[visualfoxpro]=Visual Fox Pro
ClassDescription[visualprolog]=Visual Prolog
ClassDescription[whitespace]=Whitespace
ClassDescription[whois]=Whois (RPSL format)
ClassDescription[winbatch]=Winbatch
ClassDescription[xpp]=X++
ClassDescription[xbasic]=XBasic
ClassDescription[xml]=XML
ClassDescription[xorg_conf]=Xorg configuration
ClassDescription[yaml]=YAML
ClassDescription[z80]=ZiLOG Z80 Assembler
ClassDescription[zxbasic]=ZXBasic

*/ ?>
