<?php /*

[literal]
AvailableClasses[]=abap
AvailableClasses[]=actionscript
AvailableClasses[]=actionscript3
AvailableClasses[]=ada
AvailableClasses[]=apache
AvailableClasses[]=applescript
AvailableClasses[]=apt_sources
AvailableClasses[]=asm
AvailableClasses[]=asp
AvailableClasses[]=autoit
AvailableClasses[]=avisynth
AvailableClasses[]=bash
AvailableClasses[]=basic4gl
AvailableClasses[]=blitzbasic
AvailableClasses[]=bnf
AvailableClasses[]=boo
AvailableClasses[]=bf
AvailableClasses[]=c
AvailableClasses[]=csharp
AvailableClasses[]=c_mac
AvailableClasses[]=cpp
AvailableClasses[]=cpp-qt
AvailableClasses[]=caddcl
AvailableClasses[]=cadlisp
AvailableClasses[]=cfdg
AvailableClasses[]=cil
AvailableClasses[]=cobol
AvailableClasses[]=cfm
AvailableClasses[]=css
AvailableClasses[]=d
AvailableClasses[]=delphi
AvailableClasses[]=diff
AvailableClasses[]=div
AvailableClasses[]=dos
AvailableClasses[]=dot
AvailableClasses[]=eiffel
AvailableClasses[]=email
AvailableClasses[]=ezini
AvailableClasses[]=eztemplate
AvailableClasses[]=fortran
AvailableClasses[]=freebasic
AvailableClasses[]=genero
AvailableClasses[]=glsl
AvailableClasses[]=gml
AvailableClasses[]=gettext
AvailableClasses[]=make
AvailableClasses[]=gnuplot
AvailableClasses[]=groovy
AvailableClasses[]=haskell
AvailableClasses[]=hq9plus
AvailableClasses[]=html4strict
AvailableClasses[]=ini
AvailableClasses[]=inno
AvailableClasses[]=intercal
AvailableClasses[]=io
AvailableClasses[]=java
AvailableClasses[]=java5
AvailableClasses[]=javascript
AvailableClasses[]=kixtart
AvailableClasses[]=klonec
AvailableClasses[]=klonecpp
AvailableClasses[]=latex
AvailableClasses[]=lisp
AvailableClasses[]=lolcode
AvailableClasses[]=lotusformulas
AvailableClasses[]=lotusscript
AvailableClasses[]=lscript
AvailableClasses[]=lua
AvailableClasses[]=matlab
AvailableClasses[]=mpasm
AvailableClasses[]=reg
AvailableClasses[]=mirc
AvailableClasses[]=m68k
AvailableClasses[]=mxml
AvailableClasses[]=mysql
AvailableClasses[]=nsis
AvailableClasses[]=objc
AvailableClasses[]=ocaml
AvailableClasses[]=ocaml-brief
AvailableClasses[]=oobas
AvailableClasses[]=oracle8
AvailableClasses[]=oracle11
AvailableClasses[]=pascal
AvailableClasses[]=per
AvailableClasses[]=perl
AvailableClasses[]=php
AvailableClasses[]=php-brief
AvailableClasses[]=pic16
AvailableClasses[]=pixelbender
AvailableClasses[]=plsql
AvailableClasses[]=powershell
AvailableClasses[]=povray
AvailableClasses[]=progress
AvailableClasses[]=prolog
AvailableClasses[]=providex
AvailableClasses[]=python
AvailableClasses[]=qbasic
AvailableClasses[]=rails
AvailableClasses[]=robots
AvailableClasses[]=ruby
AvailableClasses[]=sas
AvailableClasses[]=scala
AvailableClasses[]=scheme
AvailableClasses[]=scilab
AvailableClasses[]=sdlbasic
AvailableClasses[]=smalltalk
AvailableClasses[]=smarty
AvailableClasses[]=sql
AvailableClasses[]=tsql
AvailableClasses[]=tcl
AvailableClasses[]=teraterm
AvailableClasses[]=text
AvailableClasses[]=thinbasic
AvailableClasses[]=typoscript
AvailableClasses[]=idl
AvailableClasses[]=vbnet
AvailableClasses[]=verilog
AvailableClasses[]=vhdl
AvailableClasses[]=vim
AvailableClasses[]=vb
AvailableClasses[]=visualfoxpro
AvailableClasses[]=visualprolog
AvailableClasses[]=whitespace
AvailableClasses[]=winbatch
AvailableClasses[]=xpp
AvailableClasses[]=xml
AvailableClasses[]=xorg_conf
AvailableClasses[]=z80

ClassDescription[abap]=ABAP
ClassDescription[actionscript]=ActionScript
ClassDescription[actionscript3]=ActionScript 3
ClassDescription[ada]=Ada
ClassDescription[apache]=Apache configuration
ClassDescription[applescript]=AppleScript
ClassDescription[apt_sources]=Apt sources
ClassDescription[asm]=ASM
ClassDescription[asp]=ASP
ClassDescription[autoit]=AutoIt
ClassDescription[avisynth]=AviSynth
ClassDescription[bash]=Bash
ClassDescription[basic4gl]=Basic4GL
ClassDescription[blitzbasic]=BlitzBasic
ClassDescription[bnf]=bnf
ClassDescription[boo]=Boo
ClassDescription[bf]=Brainfuck
ClassDescription[c]=C
ClassDescription[csharp]=C#
ClassDescription[c_mac]=C (Mac)
ClassDescription[cpp]=C++
ClassDescription[cpp-qt]=C++ (QT)
ClassDescription[caddcl]=CAD DCL
ClassDescription[cadlisp]=CAD Lisp
ClassDescription[cfdg]=CFDG
ClassDescription[cil]=CIL
ClassDescription[cobol]=COBOL
ClassDescription[cfm]=ColdFusion
ClassDescription[css]=CSS
ClassDescription[d]=D
ClassDescription[delphi]=Delphi
ClassDescription[diff]=Diff
ClassDescription[div]=DIV
ClassDescription[dos]=DOS
ClassDescription[dot]=dot
ClassDescription[eiffel]=Eiffel
ClassDescription[email]=eMail (mbox)
ClassDescription[ezini]=eZ Publish ini
ClassDescription[eztemplate]=eZ Publish template
ClassDescription[fortran]=Fortran
ClassDescription[freebasic]=FreeBasic
ClassDescription[genero]=genero
ClassDescription[glsl]=glSlang
ClassDescription[gml]=GML
ClassDescription[gettext]=GNU Gettext
ClassDescription[make]=GNU make
ClassDescription[gnuplot]=Gnuplot
ClassDescription[groovy]=Groovy
ClassDescription[haskell]=Haskell
ClassDescription[hq9plus]=HQ9+
ClassDescription[html4strict]=HTML
ClassDescription[ini]=INI
ClassDescription[inno]=Inno
ClassDescription[intercal]=INTERCAL
ClassDescription[io]=Io
ClassDescription[java]=Java
ClassDescription[java5]=Java(TM) 2 Platform Standard Edition 5.0
ClassDescription[javascript]=Javascript
ClassDescription[kixtart]=KiXtart
ClassDescription[klonec]=KLone C
ClassDescription[klonecpp]=KLone C++
ClassDescription[latex]=LaTeX
ClassDescription[lisp]=Lisp
ClassDescription[lolcode]=LOLcode
ClassDescription[lotusformulas]=Lotus Notes @Formulas
ClassDescription[lotusscript]=LotusScript
ClassDescription[lscript]=LScript
ClassDescription[lua]=Lua
ClassDescription[matlab]=Matlab M
ClassDescription[mpasm]=Microchip Assembler
ClassDescription[reg]=Microsoft Registry
ClassDescription[mirc]=mIRC Scripting
ClassDescription[m68k]=Motorola 68000 Assembler
ClassDescription[mxml]=MXML
ClassDescription[mysql]=MySQL
ClassDescription[nsis]=NSIS
ClassDescription[objc]=Objective-C
ClassDescription[ocaml]=OCaml
ClassDescription[ocaml-brief]=OCaml (brief)
ClassDescription[oobas]=OpenOffice.org Basic
ClassDescription[oracle8]=Oracle 8 SQL
ClassDescription[oracle11]=Oracle 11 SQL
ClassDescription[pascal]=Pascal
ClassDescription[per]=per
ClassDescription[perl]=Perl
ClassDescription[php]=PHP
ClassDescription[php-brief]=PHP (brief)
ClassDescription[pic16]=PIC16
ClassDescription[pixelbender]=Pixel Bender 1.0
ClassDescription[plsql]=PL/SQL
ClassDescription[powershell]=posh
ClassDescription[povray]=POVRAY
ClassDescription[progress]=Progress
ClassDescription[prolog]=Prolog
ClassDescription[providex]=ProvideX
ClassDescription[python]=Python
ClassDescription[qbasic]=QBasic/QuickBASIC
ClassDescription[rails]=Rails
ClassDescription[robots]=robots.txt
ClassDescription[ruby]=Ruby
ClassDescription[sas]=SAS
ClassDescription[scala]=Scala
ClassDescription[scheme]=Scheme
ClassDescription[scilab]=SciLab
ClassDescription[sdlbasic]=sdlBasic
ClassDescription[smalltalk]=Smalltalk
ClassDescription[smarty]=Smarty
ClassDescription[sql]=SQL
ClassDescription[tsql]=T-SQL
ClassDescription[tcl]=TCL
ClassDescription[teraterm]=Tera Term Macro
ClassDescription[text]=Text
ClassDescription[thinbasic]=thinBasic
ClassDescription[typoscript]=TypoScript
ClassDescription[idl]=Uno Idl
ClassDescription[vbnet]=vb.net
ClassDescription[verilog]=Verilog
ClassDescription[vhdl]=VHDL
ClassDescription[vim]=Vim Script
ClassDescription[vb]=Visual Basic
ClassDescription[visualfoxpro]=Visual Fox Pro
ClassDescription[visualprolog]=Visual Prolog
ClassDescription[whitespace]=Whitespace
ClassDescription[winbatch]=Winbatch
ClassDescription[xpp]=X++
ClassDescription[xml]=XML
ClassDescription[xorg_conf]=Xorg configuration
ClassDescription[z80]=ZiLOG Z80 Assembler

*/ ?>
